'''
Created on 2013-10-24

@author: oilbeater
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
def fib():
    a,b = 0,1
    while a < 4000000:
        yield a
        a,b = b,a + b

result = sum((i for i in fib() if i % 2 == 0))
print str(result)